logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Emails (to send the login codes)
app.mailFrom: studies@example.com
spring.mail.host: smtp.example.com
spring.mail.port: 587
spring.mail.username: studies@example.com
spring.mail.password: xxxxxxxxxxx
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

spring.mongodb.uri: mongodb+srv://xxxxxxxxxxx/?retryWrites=true&w=majority
spring.mongodb.database: xxxxxxxxxxx

google.tts.userjson: google-service-account.json

app.googleAnalyticsId:
spring.session.timeout: 1209600

spring.ai.openai.base-url: https://localai.myhost.com
spring.ai.openai.api-key: xxxxxxxxxxx
spring.ai.openai.chat.options.model: gemma4:12b
