openRewriteVersion=7.35.0
openRewriteRecipeBomVersion=3.33.0
openRewriteSpringVersion=6.33.0

benManesVersionsVersion=0.54.0
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
nodeGradleVersion=7.1.0

springAiVersion=2.0.0-M4

jlSmalltoolsMongodbVersion=4.3.0
googleCloudLibrariesBomVersion=26.84.0
flapdoodleMongoVersion=4.33.0
springSessionMongodbVersion=4.0.0-M2
